# Generated by Django 5.2.3 on 2025-06-14 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0003_journalentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='journal_attachments/'),
        ),
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SessionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('requested_time', models.TimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_duration', models.PositiveIntegerField(default=60, help_text='Duration in minutes')),
                ('session_notes', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_requests_made', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Session Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
