# Generated by Django 5.2.3 on 2025-06-14 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0004_alter_journalentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='sessionrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='attachment_file',
        ),
        migrations.RemoveField(
            model_name='sessionrequest',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='sessionrequest',
            name='session_duration',
        ),
        migrations.RemoveField(
            model_name='sessionrequest',
            name='session_notes',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='specializations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TherapistApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('license_document', models.FileField(blank=True, null=True, upload_to='therapist_docs/licenses/')),
                ('id_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='therapist_docs/ids/')),
                ('professional_photo', models.ImageField(blank=True, null=True, upload_to='therapist_docs/photos/')),
                ('motivation_statement', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True, null=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
