# Generated by Django 5.2.3 on 2025-06-14 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0005_alter_journalentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AlterModelOptions(
            name='sessionrequest',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Session Requests'},
        ),
        migrations.AlterModelOptions(
            name='therapistapplication',
            options={'verbose_name_plural': 'Therapist Applications'},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='journal_attachments/'),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='session_duration',
            field=models.PositiveIntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='session_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='therapistapplication',
            name='id_document',
            field=models.FileField(default='', upload_to='therapist_docs/ids/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapistapplication',
            name='id_number',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapistapplication',
            name='license_document',
            field=models.FileField(default='', upload_to='therapist_docs/licenses/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapistapplication',
            name='license_number',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapistapplication',
            name='motivation_statement',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapistapplication',
            name='professional_photo',
            field=models.ImageField(default='', upload_to='therapist_docs/photos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
