# Generated by Django 5.2.3 on 2025-06-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0006_alter_journalentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistapplication',
            name='specializations',
            field=models.CharField(blank=True, help_text='Comma-separated list of specializations', max_length=255, null=True),
        ),
    ]
