# Generated by Django 5.2.3 on 2025-06-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0008_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistapplication',
            name='approach_modalities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='client_focus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='insurance_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='languages_spoken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='license_credentials',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='approach_modalities',
            field=models.TextField(blank=True, help_text='e.g., CBT, EMDR, Psychodynamic', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='client_focus',
            field=models.TextField(blank=True, help_text='e.g., Adults, Teens, LGBTQ+, Couples', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='insurance_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text='Comma-separated list of languages', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_credentials',
            field=models.CharField(blank=True, help_text='e.g., LMFT, LCSW, PhD', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='video_introduction_url',
            field=models.URLField(blank=True, help_text='Link to a brief video introduction', max_length=500, null=True),
        ),
    ]
