# Generated by Django 5.2.3 on 2025-06-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0009_therapistapplication_approach_modalities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='zoom_meeting_url',
            field=models.URLField(blank=True, help_text='Zoom meeting URL for online sessions', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='is_free_consultation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='physical_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='session_modes',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('physical', 'Physical (In-Person)'), ('both', 'Both Online & Physical')], default='online', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_free_consultation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='physical_address',
            field=models.TextField(blank=True, help_text='Physical address for in-person sessions', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='session_modes',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('physical', 'Physical (In-Person)'), ('both', 'Both Online & Physical')], default='online', max_length=50, null=True),
        ),
    ]
