# Generated by Django 5.2.3 on 2025-06-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0011_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistapplication',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
