# Generated by Django 5.2.3 on 2025-06-20 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0013_payment_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField(help_text='Start of available working hours for the day')),
                ('end_time', models.TimeField(help_text='End of available working hours for the day')),
                ('break_start_time', models.TimeField(blank=True, help_text='Start of an optional break (e.g., lunch)', null=True)),
                ('break_end_time', models.TimeField(blank=True, help_text='End of an optional break (e.g., lunch)', null=True)),
                ('slot_duration', models.PositiveIntegerField(default=60, help_text='Duration of each bookable session slot in minutes (e.g., 60 for 1-hour sessions)')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Therapist Availabilities',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('therapist', 'day_of_week')},
            },
        ),
    ]
