# Generated by Django 5.2.3 on 2025-06-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0014_therapistavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=120, help_text='Duration of the session in minutes'),
        ),
    ]
