# Generated by Django 5.2.3 on 2025-06-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0015_session_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrequest',
            name='session_duration',
            field=models.PositiveIntegerField(default=120, help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='therapistavailability',
            name='slot_duration',
            field=models.PositiveIntegerField(default=120, help_text='Duration of each bookable session slot in minutes (e.g., 60 for 1-hour sessions)'),
        ),
    ]
