# Generated by Django 5.2.3 on 2025-07-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0018_remove_chatmessage_room_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_modes',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('physical', 'Physical (In-Person)'), ('both', 'Both Online & Physical')], default='online', max_length=50, null=True),
        ),
    ]
